baseURL = 'https://temp.falk-m.de/'
languageCode = 'en-us'
title = 'ChaosZone'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Members'
pageRef = '/members'
weight = 20

[[menus.main]]
name = 'Projects'
pageRef = '/projects'
weight = 20

[[menus.main_future]]
name = 'Events'
pageRef = ''
weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
